on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false # If one OS fails, still try the others
      matrix:
        os: [macos-latest, ubuntu-latest] # windows-latest is buggy currently, skip CI
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: npm install
    - run: npm install -g typescript
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
